### ISSUE TITLE
Proxy web is offline

### ISSUE THREAD

**Issue by santiagomgv** [net-guy/citaq#1]
Good afternoon, Is there something similar to the proxy since the web does not work?  Thank you :)

**Comment by orbing** [comment]
Hello there,
Sorry for taking a long time to get back to you. If you're referring to the WiFi issue mentioned, try connecting the device to your router using the Ethernet port on the back of your device, this should solve your connectivity issues. 

As of current, I do not have a patch or device drivers for the on-board WiFi. After resetting the device to factory you loose the ability to connect to wifi/bluetooth.

The SDK for the Citaq H10 device can be found here [r/Citaq](https://www.reddit.com/r/citaq/comments/nivm5m/citaq_android_source_code_library/). Have a look through there you may find something interesting.

**Comment by santiagomgv** [comment]
I mean the printproxy3.apk :/ I am not able to detect the thermal printer with the loyverse tpv or similar to print tickets.

**Comment by net-guy** [comment]
I can look into this for you. So I can properly troubleshoot this, I need you to answer a few questions for me. 

Are you using the Loyverse App on the Citaq device, or trying to connect from a separate device?
Is this issue the same when connecting from other similar apps?
Is your device properly connected to your network and can receive requests? (Try steps below)

To see if the Citaq device is properly connected to the network, try the following:
- Have the Print Proxy App open on the Citaq Device
- The app should display the devices LAN IP address and port.
- Enter both these into your web browser, on another device, in the follow format ` http://<IP>:<PORT>/ `
- Citaq device should immediately print the HTTP headers. Your device is connected!

I have got my Citaq device in storage, so I'll have to go get it, but once I have it I'll try recreate your setup.

**Comment by net-guy** [comment]
It seems the developer has abandoned this project. Marking issue as closed,
