### ISSUE TITLE
After factory reset, did you get a buzzer tone and random cutting?

### ISSUE THREAD

**Issue by mofosyne** [net-guy/citaq#7]
Was able to do a factory reset, but found that the POS test app could not run the printer. Also after a reboot it sounds a buzzer and randomly cuts.

I am wondering if you had any issue with the printer?

**Comment by net-guy** [comment]
I haven't come across anything like your describing.
Is the buzzing and cutting continuous? Or does it only occur for a time, then stop?

Some things to try:
> Ensuring all cable connections to the main board are secure. They may have come loose while resetting the unit.
> The metal frame the connects the main board/screen to the body is latching properly when closed.

**Comment by mofosyne** [comment]
Thanks, I've isolated it to just the printer. The buzzer is connected to the printer controller MCU.
And when I completely remove the tablet the printer itself still randomly cuts and buzzes.

Opened it up to check if it's any obvious cable issue, can't see any specific issue.
I did measure low resistance across the power smoothing capacitor next to the MCU...
I suspect there is some sort of short somewhere on the board... since it still beeps randomly even with everything disconnected from the board.

I can't quite trace down the issue and do not think it is worth the time figuring it out, since I already got a second device with a working printer.

Decided to disable the printer feature completely and turn it into a printerless kiosk by shorting out Pin 3 and Pin 7 of J101 header pin from `Printer & Interface Board V3.3`. This ensures other features besides the cash register output should remain working, while keeping the change to a minimum in case I actually do want to figure out how to fix it.

-----

# Printer & Interface Board V3.3 (Investigation Log)

* Printer Controller MCU: 
    - STM32F105 (ARM MCU)
    - IC Package is LQFP64
    - https://www.st.com/resource/en/datasheet/stm32f105r8.pdf

* J101 (Possible Debug Port) :
    1. Pin 46 - PA13 (Suspect it's a serial port)
    2. Pin 49 - PA14 (Suspect it's a serial port)
    3. VSS - GND
    4. VDD - VCC
    5. Pin 7 - NRST

----

Image for visual reference and in case required for future documentation

## Printer & Interface Board V3.3 with Printer Controller held in reset via soldering on orange wire

![photo_2023-09-07_10-03-49](https://github.com/net-guy/citaq/assets/827793/82ed848c-2c1f-4203-a312-3d1406408abc)

## Tablet to Printer body connection

Found out you only need the large long connector to the left to have the tablet turn on.

As for the smaller 5 wire connector... it's possibly for the printer or ethernet. Unsure and not interested in investigating further as of this point.

![photo_2023-09-07_10-05-36](https://github.com/net-guy/citaq/assets/827793/325c3f50-6f51-452a-a684-467a1710cc95)
![photo_2023-09-07_10-05-42](https://github.com/net-guy/citaq/assets/827793/908ebb1e-2feb-4acd-8b11-65166b83831e)

**Comment by mofosyne** [comment]
Oh and we can close this ticket, unless there is any specific information in this, that you think would be worth transferring to the readme

**Comment by net-guy** [comment]
No worries, will sort this when I get to work 👍
